# -*- coding: utf-8 -*-
"""IA_Ejercicio_Joel_Corrales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQOeiRXdt4XKUBRi62n11oEL25qDlbVH
"""

pip install transformers torch deep_translator

#Cargar las librerias
from transformers import pipeline
from deep_translator import GoogleTranslator
import torch

# Detectar si hay GPU disponible
device = 0 if torch.cuda.is_available() else -1

# Cargar el modelo
generar_modelo = pipeline(
    'text-generation',
    model='EleutherAI/gpt-neo-1.3B',
    device=device,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

def calculo_matematicos():
    print("Introduce una operación matemática [Ej: ⓻ + ⓽ ]: ")
    operacion = input()
    try:
        resultado = eval(operacion)
        print(f"El resultado Σ es: {resultado}")
    except Exception as e:
        print(f"Error: {e}")

def manipular_texto():
    print("¿Qué deseas hacer con el texto? ✍" )
    print("1. Contar palabras ☝")
    print("2. Convertir a mayúsculas Ⓐ")
    print("3. Convertir a minúsculas ⓐ")
    opcion = input("Elige una opción [1, 2, 3]: ")

    texto = input("Introduce el texto: ")

    if opcion == '1':
        print(f"El texto que ingresaste tiene un total de {len(texto.split())} palabras.")
    elif opcion == '2':
        print(f"Conversión de texto en mayúsculas Ⓐ: {texto.upper()}")
    elif opcion == '3':
        print(f"Conversión de texto en minúsculas ⓐ: {texto.lower()}")
    else:
        print("Opción No existente")

def responder_preguntas():
    pregunta = input("¿En que puedo ayudarte? ")

    # Traducir la pregunta al inglés
    pregunta_ingles = GoogleTranslator(source='es', target='en').translate(pregunta)

    # Generar la respuesta en inglés con mejor control de repeticiones
    respuestas = generar_modelo(
        pregunta_ingles,
        max_length=30,
        num_return_sequences=1,
        do_sample=True,
        temperature=0.6,
        pad_token_id=50256,
        top_k=50,
        top_p=0.9,
        repetition_penalty=2.0,
        truncation=True
    )

    respuesta_ingles = respuestas[0]['generated_text'].replace(pregunta_ingles, "").strip()

    # Traducir la respuesta al español
    respuesta = GoogleTranslator(source='en', target='es').translate(respuesta_ingles)

    print(f"Respuesta: {respuesta}")

# Menú interactivo
def menu():
  print("\nTe doy la bienvenida al Asistente de IA Conversacional")
  while True:
    print("\nA continuación te presento la lista de cosas que puedo hacer:")
    print("1. Realizar cálculos matemáticos")
    print("2. Manipular texto")
    print("3. Responder preguntas generales")
    print("4. Finalizar")

    opcion = input("Elige una opción (1, 2, 3, 4): ")

    if opcion == '1':
      calculo_matematicos()
    elif opcion == '2':
      manipular_texto()
    elif opcion == '3':
      responder_preguntas()
    elif opcion == '4':
      print("Gracias por usar el asistente IA. ¡Hasta luego! 👋")
      break
    else:
      print("Opción no válida. Inténtalo de nuevo.")

menu()